Pull request for the Using Bootstrap project
euqueme/using-bootstrap pull request #1
Opened 2019-10-04 17:34 UTC by euqueme

to whom it concerns: 
I have a warning(not error) on line #815 because the Magazine is a section but its also just an image with no text.

Thank you in advance for your kind review 💃

2019-10-04 20:25 UTC, whiz25 commented on index.html
> +    <!-- Required meta tags -->
remove comment

2019-10-04 20:25 UTC, whiz25 commented on index.html
> +    <!-- Bootstrap CSS -->
this too

2019-10-04 20:34 UTC, whiz25 requested changes
## Amazing job :+1:  @euqueme 
Your project looks awesome and am impressed with the effort you have put into it.
This project meets most of the requirements but we need to fix a few minor things before we can merge. Check my suggestions below
- [x] your navbar needs a fix below ```320px```. compare it the original site.
- [x] given that this is a clone, please add a ```hamburger menu``` for screens below ```768px```
- [x] remove all comments from your code.
- [x] clone the original site as close as possible.

Please send for another review when you done.

2019-10-07 12:52 UTC, euqueme commented
to whom it concerns:
I didn't made the fix at 320px on the navbar originally because Bootstrap doesn't have a breakpoint at mentioned screen size so to accomplish this I had to use a media query.

Thank you in advance for your kind review 💃

2019-10-07 17:13 UTC, whiz25 approved these changes
## Awesome job :clap: @euqueme 
You have implemented all the suggested changes and therefore it's a :+1: from me.
Use ```Martin Afani``` when filling the form. Good luck in your up coming projects.

2019-10-07 23:01 UTC, merged